plugin_format_version: 2
name: admin-ui-conference
namespace: official
version: 1.1.0-4
author: Wazo Team
display_name: Conference
min_wazo_version: 18.01
tags:
  - application
homepage: https://github.com/wazo-pbx/wazo-admin-ui-conference
depends:
  - name: admin-ui-context
    namespace: official
    version: ">= 1.1.1-2"
  - name: admin-ui-extension
    namespace: official
    version: ">= 1.2.0-2"
