name: admin-ui-conference
namespace: official
version: 1.1.0-6
author: Wazo Team
display_name: Conference
min_wazo_version: 18.02
tags:
  - application
homepage: https://github.com/wazo-pbx/wazo-admin-ui-conference
depends:
  - name: admin-ui-context
    namespace: official
  - name: admin-ui-extension
    namespace: official
