name: admin-ui-conference
namespace: official
version: 0.0.2
author: Wazo Team
display_name: Conference
min_wazo_version: 17.16
tags:
  - beta
  - application
homepage: https://github.com/wazo-pbx/wazo-admin-ui-conference

