name: admin-ui-conference
namespace: official
version: 1.1.0
author: Wazo Team
display_name: Conference
min_wazo_version: 17.17
tags:
  - beta
  - application
homepage: https://github.com/wazo-pbx/wazo-admin-ui-conference

